### ISSUE TITLE
Make the UI less ugly

### ISSUE THREAD

**Issue by H3rmt** [H3rmt/hyprswitch#15]

**Comment by H3rmt** [comment]
fix layout-shifting from index changing

**Comment by H3rmt** [comment]
Add a floating Index (TODO find out how to so that in GTK4)

**Comment by SergioRibera** [comment]
It would be nice if the application could load a custom css, that would help a lot too

**Comment by H3rmt** [comment]
> It would be nice if the application could load a custom css, that would help a lot too

The CSS is currently hardcoded in https://github.com/H3rmt/hyprswitch/blob/master/src/gui.rs#L20, but im planing to add a cli frag to specify a custom css file

**Comment by H3rmt** [comment]
``--custom-css`` just added
