### ISSUE TITLE
Possibility to only show the GUI on one monitor

### ISSUE THREAD

**Issue by lunatic-gh** [H3rmt/hyprswitch#20]
Hey, i really like this app, but there's one issue i have.

I couldn't give a single damn about those workspaces. I use 3 monitors, and therefore (apparently?) 3 workspaces (even tho i'd prefer to use only one across all monitors, but seemingly not possible in hyprland...)

Now, what i want is to include all window's apps, but only show the GUI itself on my main monitor.

I've read that maybe that's what --ignore-monitors is supposed to do, but i don't get that offset thing... you don't actually mean i have to now create 30 empty workspaces just for this to work?

**Comment by H3rmt** [comment]
> Now, what i want is to include all window's apps, but only show the GUI itself on my main monitor.

This is currently not possible, as every monitor gets its own GUI with its workspaces, i might add a `--monitor-id` in the future to only show the gui on one monitor

**Comment by H3rmt** [comment]
> I've read that maybe that's what --ignore-monitors is supposed to do, but i don't get that offset thing... you don't actually mean i have to now create 30 empty workspaces just for this to work?

the `--ignore-monitors` is only relevant for sorting the windows:

- Order without `--ignore-monitors` 
```
                   Monitor 1                                   Monitor 2
       Workspace 0           Workspace 1           Workspace 10          Workspace 11
 1  +------+  +------+ | +------+  +------+  |  +------+  +------+ | +------+  +------+
 2  |  1   |  |  2   | | |  5   |  |  6   |  |  |  9   |  |  10  | | |  13  |  |  14  |
 3  |      |  |      | | |      |  +------+  |  |      |  |      | | |      |  +------+
 4  +------+  +------+ | +------+  +------+  |  +------+  +------+ | +------+  +------+
 5  +------+  +------+ | +------+  |  8   |  |  +---------+  +---+ | +------+  |  16  |
 6  |  3   |  |  4   | | |  7   |  |      |  |  |   11    |  |12 | | |  15  |  |      |
 7  +------+  +------+ | +------+  +------+  |  +---------+  +---+ | +------+  +------+
    1      2  3      4   1      2  3      4     5      6  7  8   9   5      6  7   8  9
```
- Order with `--ignore-monitors` 
```
                   Monitor 1                                   Monitor 2
       Workspace 0           Workspace 1           Workspace 10          Workspace 11
 1  +------+  +------+ | +------+  +------+  |  +------+  +------+ | +------+  +------+
 2  |  1   |  |  2   | | |  9   |  |  10  |  |  |  3   |  |  4   | | |  11  |  |  12  |
 3  |      |  |      | | |      |  +------+  |  |      |  |      | | |      |  +------+
 4  +------+  +------+ | +------+  +------+  |  +------+  +------+ | +------+  +------+
 5  +------+  +------+ | +------+  |  14  |  |  +---------+  +---+ | +------+  |  16  |
 6  |  5   |  |  6   | | |  13  |  |      |  |  |   7     |  | 8 | | |  15  |  |      |
 7  +------+  +------+ | +------+  +------+  |  +---------+  +---+ | +------+  +------+
    1      2  3      4   1      2  3      4     5      6  7  8   9   5      6  7  8   9
```

The offset of 10 is currently required because the windows from workspace 1 and 11(1 + 10) get combined together, but you can just have one workspace with id=1 on monitor 1 and one workspace with id=11 on monitor 2

**Comment by lunatic-gh** [comment]
Ah i see, thanks for the help then!
