### ISSUE TITLE
sort-recent on GUI

### ISSUE THREAD

**Issue by aloispichler** [H3rmt/hyprswitch#23]
Thank you again for hyprswitch. It is very good, an excellent app, it allowed me (finally) switching to hyprland.
Coming from Windows, XFCE, Gnome, I am – since years – used to the option `--sort-recent`. My config sets this option anywhere. I'd like to report minor ‘issues’.

The option `--sort-recent` activates the Apps in correct order, the functionality is as expected. Perfect.

However, the GUI displays (from left to right) workspace 1, then workspace 2, etc.
Instead, I expect the GUI to display the timeline, i.e., (from left to right) App1, App2, etc., as activated.

Example: Let’s say I have activated
Thunderbird on Workspace 8, then Kitty on workspace 2 and finally Firefox on Workspace 3.
Then the GUI displays (from left to right): Kitty, then Firefox and Thunderbird (they are sorted by workspaces).
But I expect (from left to right): Firefox (left), then Kitty, Thunderbird (right): as activated, irrespective of the workspaces.
Actually, I thought that `--ignore-workspaces` would do this job, but it serves some other purpose.

Here is my config:
```
$submap_switch =   switch window 
# allows repeated switching with same keypress that starts the submap
binde=ALT, TAB, exec, hyprswitch --daemon --sort-recent --ignore-workspaces --do-initial-execute
bind=ALT, TAB, submap, $submap_switch

# allows repeated switching with same keypress that starts the submap
binde=ALT SHIFT, TAB, exec, hyprswitch --daemon --sort-recent --ignore-workspaces --do-initial-execute --reverse
bind=ALT SHIFT, TAB, submap, $submap_switch
#
submap=$submap_switch
	# allow repeated window switching in submap (same keys as repeating while starting)
	binde=ALT, TAB, exec, hyprswitch --daemon --sort-recent --ignore-workspaces
	binde=ALT SHIFT, TAB, exec, hyprswitch --daemon --sort-recent --ignore-workspaces --reverse

	# exit submap and kill hyprswitch
	bindrt=ALT, ALT_L, exec, hyprswitch --stop-daemon
	bindrt=ALT, ALT_L, submap, reset

	# if it somehow doesn't close on releasing $switch_release, escape can close too
	bindr=,escape, exec, hyprswitch --stop-daemon
	bindr=,escape, submap, reset
submap=reset
```

**Comment by H3rmt** [comment]
All CLI arguments under the `Sorting related` section only change the order of windows, not how they are displayed in the UI

The UI displays the windows based on their actual position to mimic your desktop.

[v1.2.0](https://github.com/H3rmt/hyprswitch/releases/tag/v1.2.0) now shows the order of windows in the bottom right corner, but I have no plans to rewrite the UI to display the windows in the order they would be selected, (i also dont know how that should look with more than one window per workspace).

**Comment by aloispichler** [comment]
Hello again. This code snippet above used to trigger on _release_ of `Alt+Tab`. However, the _release functionality_ stopped working a week ago or so. Any ideas?

**Comment by H3rmt** [comment]
@aloispichler the Gui-keyboard config seems broken, it seems like the release of the modifier key doesn't close hyprswitch any more

**Comment by H3rmt** [comment]
Just switched to the git version of hyprland and it just works again (I use bindrt to close with the same key press that opened hyprswitch)

**Comment by H3rmt** [comment]
> Here is another point: the GUI highlights the selected app by changing the color of its border to red. Using the laptop outdoors, this is often barely visible.

I made red a bit brighter, but the next release allows for custom css so you can just add ```css
.client_active {
    border: 3px solid rgba(239, 9, 9, 0.94);
    background-color: rgba(200, 9, 9, 0.80);
}
```
to a css file and include it with the new --custom-css flag

**Comment by aloispichler** [comment]
Looks nice and works well. Thank you!
