### ISSUE TITLE
flickering

### ISSUE THREAD

**Issue by aloispichler** [H3rmt/hyprswitch#24]
I am using thunderbird and firefox. Both react on hitting and releasing `ALT` (they display/ hide the menu). Switching to firefox or to thunderbird seems to send an additional `alt` and `release alt` to the app, which causes some flickering. Of course, this is not an important issue, but perhaps this can be avoided.
See my other issue for the config.
Thanks again.

**Comment by H3rmt** [comment]
I don't know if there is a modifier for a Hyprland bind that prevents dispatching the press of the modifier key (ALT) to the current application. Hyprland cannot know whether you press TAB after pressing ALT to open hyprswitch or if you want to show the menu in Firefox so I dont know if they will add one.

**Comment by H3rmt** [comment]
The best option would be to to use the Super or Ctrl key instead of Alt

**Comment by aloispichler** [comment]
Sure, this would remove the flickering. People https://alt-tab-macos.netlify.app/
