### ISSUE TITLE
Layout of floating windows workspace -> tiled in hyprswitch

### ISSUE THREAD

**Issue by stinobook** [H3rmt/hyprswitch#38]
Hello,

I use floating windows instead of tiling and hyprswitch copies the whole floating layout in the hyprswitch overview as well.

Would it be possible to tile the hyprswitch icons ?

![image](https://github.com/H3rmt/hyprswitch/assets/51697064/7e409ad8-a5f9-4b5c-879a-cfda8f8aac29)

Thanks!
Stino

**Comment by H3rmt** [comment]
Hyprswitch scales the real dimensions of the windows down by a factor of 7 and
displays them in the GUI. This works most for Users with tiling windows as this
Method uses the space in the most efficiently.

This of course does not work for users with many floating windows, but I don't know
how to fix that, as I want to also see the floating windows float inside hyprswitch.

We could display them like the Windows Application Switcher, but that would
require a lot of horizontal space, which is not available in the GUI when using many 
Workspaces.

**Comment by stinobook** [comment]
How about just adding an option so they show up 'tiled' in the workspace ? then it doesn't give issues with the rest of the layout ?

**Comment by githubkuyaya** [comment]
I second this, it would be awesome to have a Windows Application Switcher like mode. I use a lot of floating windows, so it'd be a nice addition.
Nevertheless, it's still the best application out there so far for Hyprland, thanks a lot!

**Comment by H3rmt** [comment]
This will be tracked in #62 please leave your suggestions, examples, etc. there as this doesn't really reflect the way I use hyprland so some help from you would be appreciated.

@githubkuyaya @stinobook

**Comment by H3rmt** [comment]
The problem with the missing horizontal space has also been fixed in 3.0.0 with a CLI flag for the init command

**Comment by H3rmt** [comment]
#62 will track this feature
