### ISSUE TITLE
Unable to install via either on AUR and cargo

### ISSUE THREAD

**Issue by ahmetkotanci** [H3rmt/hyprswitch#44]
Getting this errors;

```
cargo install hyprswitch
error: process didn't exit successfully: `rustc -vV` (exit status: 127)
--- stderr
rustc: error while loading shared libraries: libLLVM.so.18.1: cannot open shared object file: No such file or directory

```
```
rustc: error while loading shared libraries: libLLVM.so.18.1: cannot open shared object file: No such file or directory
error: target was empty
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: hyprswitch-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
hyprswitch - exit status 4
```

**Comment by H3rmt** [comment]
That looks like a problem with your rust installation.
What is the output of ``rustc -vV``?

**Comment by ahmetkotanci** [comment]
> `rustc -vV`

rustc: error while loading shared libraries: libLLVM.so.18.1: cannot open shared object file: No such file or directory

**Comment by H3rmt** [comment]
Output of ``cargo -vV``?

**Comment by ahmetkotanci** [comment]
> `cargo -vV`

cargo -vV
cargo 1.79.0
release: 1.79.0
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.8.0 (sys:0.4.72+curl-8.6.0 system ssl:OpenSSL/3.3.1)
os: Arch Linux Rolling Release [64-bit

**Comment by H3rmt** [comment]
maybe running ``rustup toolchain remove stable`` and ``rustup toolchain install stable`` will help?
This is definitely a rust on arch issue.

**Comment by ahmetkotanci** [comment]
> `rustup toolchain install stable`

commands not found. Im using plain `rust` package not installed `rustup`

**Comment by H3rmt** [comment]
Try reinstalling rustc or installing rustc, cargo, etc. via rustup

**Comment by ahmetkotanci** [comment]
> Try reinstalling rustc or installing rustc, cargo, etc. via rustup

Thanks for help!

**Comment by H3rmt** [comment]
Please post your solution here even if it wasn't a problem related to hyprswitch itself
