### ISSUE TITLE
order

### ISSUE THREAD

**Issue by aloispichler** [H3rmt/hyprswitch#45]
My config includes
```
exec-once= hyprswitch init &
bind= ALT,   TAB,       exec, hyprswitch gui --sort-recent --do-initial-execute
```
* With `alt+tab`, hyprswitch highlights the current app, and goes to the next app. This behavior is right, although it should highlight the following app, not the current.

* Suppose 3 apps are open, then `alt+tab+tab+…` reveals: current (1, say) then 2 then 1 then 2 then 3 and sometimes even in different order, depending on the history. This is broken: the correct order would be 2 > 3 > 1 etc., but not 1 > 2 > 1 > 3 etc.

**Comment by H3rmt** [comment]
Looks like the sort recent functionality is buggy since switching to the daemon at startup.

**Comment by H3rmt** [comment]
Should be fixed in new version

**Comment by aloispichler** [comment]
Yes, this works now. Thank you.

**Comment by aloispichler** [comment]
the new version is much more stable now – highly appreciated!!!
