### ISSUE TITLE
Is it possible to add window titles instead of application names?

### ISSUE THREAD

**Issue by tatu2011** [H3rmt/hyprswitch#46]

**Comment by H3rmt** [comment]
Should be easy, just a new CLI arg

**Comment by tatu2011** [comment]
Thanks, but I still have one more question. How to generate  css? enter this command( for example "hyprswitch --custom-css /home/tatu")?

**Comment by H3rmt** [comment]
Hyprswitch applies the default CSS (found in the README) to the GUI.

You can write a custom css file with styles for the classes described in the README to override the default CSS.

Then use the `--custom-css` option to load this file.

**Comment by tatu2011** [comment]
Thanks bro

**Comment by H3rmt** [comment]
`--show-title` added to the init command
