### ISSUE TITLE
Unable to hyprswitch init (v. 2.0.4-1) - Invalid type: integer '0'

### ISSUE THREAD

**Issue by TomasGalvao** [H3rmt/hyprswitch#47]
Tried to install hyprswitch (version 2.0.4-1) via AUR and via Cargo and this is always the output of `hyprswitch init -vv`:

``` 
$ hyprswitch -vv init

DEBUG Checking if daemon is running
DEBUG Daemon not running: Connection refused (os error 111)
INFO Starting daemon
Error: Failed to run daemon

Caused by:
    0: Failed to collect data with config Config { ignore_monitors: false, ignore_workspaces: false, sort_recent: false, filter_current_workspace: false, filter_current_monitor: false, filter_same_class: false, include_special_workspaces: true }
    1: invalid type: integer `0`, expected a boolean at line 21 column 19
```

**Comment by H3rmt** [comment]
What version of hyperland are you running?

**Comment by TomasGalvao** [comment]
Latest hyprland-git

**Comment by H3rmt** [comment]
Can you run `hyprctl clients`?

**Comment by TomasGalvao** [comment]
```
Window 55ba1af99b40 -> Visual Studio Code:
	mapped: 1
	hidden: 0
	at: 8,47
	size: 1904,1025
	workspace: 1 (1)
	floating: 0
	pseudo: 0
	monitor: 0
	class: Code
	title: Visual Studio Code
	initialClass: Code
	initialTitle: Visual Studio Code
	pid: 3268
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenClient: 0
	grouped: 0
	tags:
	swallowing: 0
	focusHistoryID: 2

Window 55ba1c327d50 -> Unable to hyprswitch init (v. 2.0.4-1) - Invalid type: integer '0' · Issue #47 · H3rmt/hyprswitch — Cachy Browser:
	mapped: 1
	hidden: 0
	at: 8,47
	size: 1904,1025
	workspace: 3 (3)
	floating: 0
	pseudo: 0
	monitor: 0
	class: cachy-browser
	title: Unable to hyprswitch init (v. 2.0.4-1) - Invalid type: integer '0' · Issue #47 · H3rmt/hyprswitch — Cachy Browser
	initialClass: cachy-browser
	initialTitle: Cachy Browser
	pid: 9151
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenClient: 0
	grouped: 0
	tags:
	swallowing: 0
	focusHistoryID: 1

Window 55ba1e6eb360 -> hyprctl clients:
	mapped: 1
	hidden: 0
	at: 198,149
	size: 1524,821
	workspace: -99 (special:special)
	floating: 0
	pseudo: 0
	monitor: 0
	class: Alacritty
	title: hyprctl clients
	initialClass: Alacritty
	initialTitle: Terminal
	pid: 21863
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenClient: 0
	grouped: 0
	tags:
	swallowing: 0
	focusHistoryID: 0
```

**Comment by vansoest** [comment]
Same issue here with latest version from AUR—exactly the same output.

**Comment by Smithx10** [comment]
same.

**Comment by H3rmt** [comment]
Seems like I have to switch to the latest hyprland-git to reproduce this

**Comment by Smithx10** [comment]
@H3rmt  I looked into it a bit,   Didn't debug it completely but I think this could be causing the serialization issue.

Looks like Hyprland refactored fullscreen.  

Hyprland-rs has a new PR that isn't upstream yet.

https://github.com/hyprland-community/hyprland-rs/pull/258

**Comment by Smithx10** [comment]
Just a followup,  bumping cargo to a local branch from that PR and fixing the sort logic here:

https://github.com/H3rmt/hyprswitch/blob/main/src/sort.rs#L200

I was able to run hyperswitch --daemona nd not have the error.

![image](https://github.com/user-attachments/assets/69f84684-4c93-4da6-b853-a584fddd6123)

**Comment by H3rmt** [comment]
Seems like I need to wait for a hyprland-rs release

**Comment by Mop-u** [comment]
hyprland-rs has bumped to 0.4.0-alpha.3, which works for me on nixos - I just had to pull the repo & ran `cargo add hyprland=@0.4.0-alpha.3`

**Comment by H3rmt** [comment]
Thanks for the Notification, I will update as soon as I get home

**Comment by H3rmt** [comment]
`hyprswitch v2.1.2` released :partying_face:

Thanks everyone for helping getting a new hyprland-rs version released
