### ISSUE TITLE
Where to apply the --switch-on-close flag

### ISSUE THREAD

**Issue by lindeMAX** [H3rmt/hyprswitch#48]
Hi,
first of all thanks for the great tool :)

I can't figure out where to apply the --switch-on-close flag.
Also the README.md is a bit missleading here as the flag is listed as gui related but does not to be applied to the gui subcommand.

PS: I'm currently running version 2.0.4 installed from AUR.
Greetings

**Comment by H3rmt** [comment]
I have not managed to complete the new 2.0 release docs for the new CLI args.
For now just follow the README in the `dev` branch

**Comment by H3rmt** [comment]
Or use `hyprswitch --help` / `hyprswitch gui --help` / etc. to see the available arguments

**Comment by H3rmt** [comment]
New Readme in the main branch
