### ISSUE TITLE
Workspace positions

### ISSUE THREAD

**Issue by lindeMAX** [H3rmt/hyprswitch#49]
Hi, 
as far as i can tell, the gui does position workspaces inside the window based on their real position.
I really like that idea but it can be an issue if there are to many workspaces to fit onto a single screen. Aka the window is getting to wide.
Would it be hard to implement some kind of scrolling or give an option do display a grid view of workspaces?
There may be another option to deal with this.

**Comment by H3rmt** [comment]
I think I have to order the workspaces via CSS, instead of using absolute positioning to make this possible

**Comment by H3rmt** [comment]
added a new env var in `2.1.3` (WORKSPACES_PER_ROW)
