### ISSUE TITLE
Option to Switch Workspaces Directly Without Cycling Through All Windows

### ISSUE THREAD

**Issue by UmmItC** [H3rmt/hyprswitch#51]
Hello!

I've been using this tool for a few weeks now, and it’s been working great. I have a couple of suggestions that could make it even better.

Currently, when switching workspaces, the tool cycles through all open windows by default. This can be cumbersome if there are many windows in the workspace. For example, if I want to switch from Workspace 1 to Workspace 3, but Workspace 2 has several windows, I end up having to tab through all the windows in Workspace 2 before reaching Workspace 3.

Here’s a scenario: 

- Workspace 1 has 1 window.
- Workspace 2 has 3 windows.
- Workspace 3 has 1 window.

If I’m on Workspace 1 and want to switch to Workspace 3, I need to tab through all 3 windows in Workspace 2 before reaching Workspace 3, totaling 4 tabs. This can be inefficient, especially when the windows are not far apart.

It would be more efficient if workspace switching could ignore the windows and just move to the next workspace directly.

Additionally, it would be beneficial if the mouse position remained unchanged during the workspace switch.

It would be great if there were an option to switch workspaces directly without cycling through all windows and without affecting the mouse position.

**Comment by H3rmt** [comment]
Seems like a good improvement, a `--switch-workspaces` flag added to the GUI / Simple commands would be suitable.

Not changing the mouse position when switching windows is not possible, this is automatically done by hyprland, as moving the cursor over another window can switch focus (if configured)

**Comment by H3rmt** [comment]
please take a look at 3.0.0-alpha.3 (docs in https://github.com/H3rmt/hyprswitch/blob/dev/README.md)
Can be installed via `cargo install hyprswitch@3.0.0-alpha.3`

**Comment by UmmItC** [comment]
after updated my system, Hyprswitch just broken. and I can't use it for now

```
❯ hyprswitch -vv init
DEBUG Checking if daemon is running
DEBUG Daemon not running: Connection refused (os error 111)
INFO Starting daemon
INFO Starting gui
INFO Starting daemon
INFO Starting listener on "/run/user/1000/hyprswitch.sock"
DEBUG Running application
Gdk-Message: 18:59:14.082: Error 12 (Cannot allocate memory) dispatching to Wayland display.

❯ hyprswitch init
Gdk-Message: 19:06:00.800: Error 12 (Cannot allocate memory) dispatching to Wayland display.

❯ hyprswitch --version
hyprswitch 3.0.0-alpha.3

❯ hyprctl version
Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 16:48:21 2024
Tag: v0.43.0, commits: 5196

flags: (if any)
```

I have no idea, what can i do :(

**Comment by H3rmt** [comment]
can you try `cargo install hyprswitch@3.0.0-alpha.4` and see if it works now?

**Comment by H3rmt** [comment]
did `3.0.0-alpha.3` work before the update?

what Hyprland version are you running?

**Comment by UmmItC** [comment]
Before the update, there were no problems with Hyprswitch. I think a Wayland update might have affected it.

I've been using version 0.43 for a while, and I had the yay version of Hyprswitch before.

I had no issues then, but after the update (-Syu), Hyprswitch stopped working, and an error appears in the upper right corner.

---

After i try `cargo install hyprswitch@3.0.0-alpha.4`, i got the same error

```
Gdk-Message: 19:53:52.294: Error 12 (Cannot allocate memory) dispatching to Wayland display.
```

i use hyprland 0.43 version.

```
❯ hyprctl version
Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 16:48:21 2024
Tag: v0.43.0, commits: 5196

flags: (if any)
```

**Comment by H3rmt** [comment]
Same with the hyprswitch aur version?

**Comment by UmmItC** [comment]
yes.

**Comment by H3rmt** [comment]
I renamed the cli flag to `--switch-type` and also added the monitor option in `3.0.0-alpha.5`.

Now the gui also shows the index only for workspace or client (monitor still missing).
It also filters monitors or workspaces with the filter flags provided (if a workspace doesnt contain any client that passes the filters it gets disabled)

**Comment by H3rmt** [comment]
I will close this issue as the switch workspaces feature got implemented, if you find out that the bug you are experiencing has any relation to hyprswitch feel free to open a new issue.
