### ISSUE TITLE
floating windows

### ISSUE THREAD

**Issue by aloispichler** [H3rmt/hyprswitch#56]
What is the syntax to include floating windows in hyprswitch (gui)?? (I hope I did not miss it in the manual)
Thanks!

**Comment by H3rmt** [comment]
Floating windows are no different from regular windows for hyprswitch

**Comment by aloispichler** [comment]
You are right. I did not see it because, on the GUI, it was hidden behind other apps.
Perhaps it would be better to bring the app – on the GUI – to the top, if selected?

**Comment by luyu-wu** [comment]
Implementing bringtotop right now. Unfortunately, it wasn't possible to hack-in with Hyprland keybind dispatchers so I'm just  dispatching it directly after the focus command!

**Comment by aloispichler** [comment]
Wouldn't it be enough to bring it to top just on YOUR GUI? This shod be possible without hacks.

**Comment by H3rmt** [comment]
The order of windows is dependent on their creation time (this has no special reason, that's just the default order)

The z-index of windows in the GUI are determined by the order they were added.

A good solution would be to add all floating windows last to let them appear on front of all windows

**Comment by H3rmt** [comment]
please take a look at 3.0.0-alpha.1 (docs in https://github.com/H3rmt/hyprswitch/blob/dev/README.md)
Can be installed via `cargo install hyprswitch@3.0.0-alpha.1`

(also fixes this problem, except for multiple floating windows covering each other)

**Comment by H3rmt** [comment]
windows now get moved to the top after being selected
