### ISSUE TITLE
Add option to close/switch on release of centain keys

### ISSUE THREAD

**Issue by littleblack111** [H3rmt/hyprswitch#57]
like --release-key="alt+tab"
for alt+tab. it will switch to the tab after both alt and tab are released

**Comment by H3rmt** [comment]
My plan is to activate a custom keymap when activating hyprswitch to remove the complex keymap from the config

**Comment by littleblack111** [comment]
Ya and the example one from the wiki need you to hold tab to select and it will choose when u release it

**Comment by H3rmt** [comment]
please take a look at 3.0.0-alpha.1 (docs in https://github.com/H3rmt/hyprswitch/blob/dev/README.md)

**Comment by littleblack111** [comment]
yep this works! ty!

**Comment by littleblack111** [comment]
@H3rmt hmm. the one with shift works. but i also have a mac, thus im use to the grave keybind for reverse(alt+grave) which doesnt seem to work...

**Comment by H3rmt** [comment]
Planing on adding custom key for reverse (can be modifier key or normal key) as I am planning to use the ` key for reverse tab.
The main question is how to allow switching with the number keys in reverse direction without the reverse key being a modifier key

**Comment by H3rmt** [comment]
try if `3.0.0-alpha.4` fixes it for you

**Comment by littleblack111** [comment]
weird syntax. but ya it works! ty

**Comment by littleblack111** [comment]
what about a esc key to close it?

**Comment by H3rmt** [comment]
You can lose with escape or by pressing the same mod+key used to open (when using the indexmod or mod close option)

**Comment by littleblack111** [comment]
if i set --close mod-key-release pressing escape wont work. but if i change my mind during alt + tab. i cant press escape.... but with --close none work. but then, i cant go the the position after releasing... maybe make sth like --close mod-key-release,none or just defauly enable escape key for --close mod-key-release

**Comment by H3rmt** [comment]
Can you show me the config you use for hyprswitch

**Comment by littleblack111** [comment]
hyprland config:
```
bind = alt, tab, exec, /home/system/.cargo/bin/hyprswitch gui --mod-key alt_l --key tab --close mod-key-release --reverse-key=key=grave && hyprswitch dispatch
bind = alt, grave, exec, /home/system/.cargo/bin/hyprswitch gui --mod-key alt_l --key tab --close mod-key-release --reverse-key=key=grave && hyprswitch dispatch -r
```

**Comment by H3rmt** [comment]
When using mod-key-release you can just release the mod key to close

**Comment by littleblack111** [comment]
ya. but that would take me to the app that is currently selected. but i want to close the gui without going anywhere. like cancel

**Comment by H3rmt** [comment]
Is hyprswitch in your path? 
Because you use the direct path in the command but then just use the name in the dispatch command

**Comment by littleblack111** [comment]
no its not. also please update the hyprswitch pkg on aur. cuz that one install to /usr/bin which is in my path

**Comment by H3rmt** [comment]
> ya. but that would take me to the app that is currently selected. but i want to close the gui without going anywhere. like cancel

Now I get it, the esc keypress in the mod-key-release doesn't work as esc is pressed together with the mod key and not recognized as close like with the other close modes

**Comment by H3rmt** [comment]
> no its not. also please update the hyprswitch pkg on aur. cuz that one install to /usr/bin which is in my path

I publish the test release to cargo, as soon as 3.0.0 is ready I will update the aur package

**Comment by littleblack111** [comment]
alright.
> Now I get it, the esc keypress in the mod-key-release doesn't work as esc is pressed together with the mod key and not recognized as close like with the other close modes
hope it get fixed soon! ty

**Comment by H3rmt** [comment]
fixed in `3.0.0-alpha.6`

**Comment by littleblack111** [comment]
confirm working. ty!

**Comment by H3rmt** [comment]
The only thing missing for the 3.0.0 release would be fixing the sort tests, adding better examples to readme, maybe some external testing and the click on monitor in the GUI to work

**Comment by H3rmt** [comment]
> nice! also, a little suggestion. it would be nice to have an option for sorting the window by when is the last time opening it...

There is (--sort-recent)

**Comment by littleblack111** [comment]
uhh. like in the gui

**Comment by H3rmt** [comment]
The Gui was meant to exactly represent a smaller version of your desktop, so the workspaces of each monitor are sorted by ID and each window is placed where it exists in the real workspace

**Comment by littleblack111** [comment]
sure... i want that option but its fine...

**Comment by littleblack111** [comment]
like window's alt + tab. its sorted by how recent the application is opened. like if i just used program a and now im in program b. Instead of sorting it by workspace. it should display program a as last option

**Comment by H3rmt** [comment]
Tracked in #62
