### ISSUE TITLE
fractional scaling causes daemon to fail to start

### ISSUE THREAD

**Issue by coyotepunk05** [H3rmt/hyprswitch#58]
monitor=eDP-1,highrr,auto,1.25:
```
hyprswitch init

(process:45218): GLib-GIO-CRITICAL **: 21:48:38.638: g_application_set_application_id: assertion 'application_id == NULL || g_application_id_is_valid (application_id)' failed
Segmentation fault (core dumped)
[ble: exit 139]
```
monitor=eDP-1,highrr,auto,1:
```
hyprswitch init
```
launches successfully

**Comment by H3rmt** [comment]
That's weird, I also use fractional scaling.
What hyprland and what hyprswitch version are you running?

**Comment by H3rmt** [comment]
can you add the -vv flag to hyprswitch and send the full output

**Comment by coyotepunk05** [comment]
```
hyprswitch init -vv

Error: Failed to parse command line arguments

Caused by:
    error: unexpected argument '-v' found
    
    Usage: hyprswitch init [OPTIONS]
    
    For more information, try '--help'.
```

**Comment by H3rmt** [comment]
What Hyprland version are you on?

**Comment by coyotepunk05** [comment]
It started with Hyprland 0.43, but continued when I rolled back to 0.42.

Hyprswitch is 2.1.3-1

**Comment by H3rmt** [comment]
Both Versions affected?

**Comment by coyotepunk05** [comment]
Yes, I am experiencing the issue on both versions.

**Comment by H3rmt** [comment]
Can you test what happens when you start the daemon without fractional scaling and activate it afterwards

**Comment by H3rmt** [comment]
This could be a gtk issue, as hyprswitch never uses anything regarding scaling on monitors.

But I can't really help you with this

**Comment by coyotepunk05** [comment]
Thanks for your time. I'll update if I figure out what it is.

**Comment by H3rmt** [comment]
You could try if the 3.0.0 alpha somehow fixes the problem (it uses a newer version of the evtl bindings, but this should probably not fix it)

You can install it with cargo

**Comment by H3rmt** [comment]
@coyotepunk05 any updates, did you try any other gtk apps?

You could try to see if the gtk4-leyer-shell is the problem, eww also uses it to display its UI (where I got the idea from), so you could try to launch it and see if it also fails

**Comment by coyotepunk05** [comment]
It resolved itself with an update to Hyprland a couple days ago. It must have been an issue with Hyprland that was preventing it from launching. I'm not sure what specific change caused it.
