### ISSUE TITLE
`hyprpm` installation

### ISSUE THREAD

**Issue by Jazztache** [H3rmt/hyprswitch#73]
Hello!

I would like it if this were installable via the hyprpm package manager Hyprland uses.
A lot of the official packages use this method as well.

Thankyou!

**Comment by H3rmt** [comment]
I don't know if you can distribute this program with hyprpm.

This isn't a plugin, as plugins run "inside" of Hyprland and need to be written in C++.

Hyprswitch is an external CLI that interfaces with Hyprland by sending commands to its socket.
