### ISSUE TITLE
Performance and Optimization issues

### ISSUE THREAD

**Issue by BinaryHarbinger** [H3rmt/hyprswitch#81]
## I'm currently sharing my dotfiles on github and since I started to use hyprswitch instead of rofi I realized hyprswitch got some optimization issues.
 
### Bad resource Ussage

» It uses near to hundred megabytes of ram on background and that does not make any sense because it is just a switcher gui It doesn't have to use resources in background.

### Being unfriendly with lower systems

» There is no way to disable fade in animation as I know. On some systems that is even a cause of lag. 

» And bad resource usage again.

## My suggestions

» Removing init system and making all of the threads start when program is launched by GUI command

» Adding more customization including showing up animation and changing border radius separately.

**I'm not able to share commits and contribute because of my situations right now but at least I wanted to tell my ideas. Rofi might be good program but hyprswitch got more potential in window switching.**

**Comment by H3rmt** [comment]
> It uses near to hundred megabytes of ram on background and that does not make any sense because it is just a switcher gui It doesn't have to use resources in background.

The GUI always exists, it just hides and shows itself. When disabling the GTK Gui the memory used in the background drops to less than 2MB, and some of this is the class to icon cache. Without this cache the Memory is less than 1.5MB. Even if all functionality is removed the program uses at least 1.4MB. With GTK it uses arround 15MB at launch (windows have never been opened) and up to 80MB when showing the GUI on my machine (with 15 windows and one monitor). I asume that more monitors could increase the memory usage, but there is not much I can do about it as nearly all memory is consumed by GTK.

> There is no way to disable fade in animation as I know. On some systems that is even a cause of lag.

All animations are done by Hyprland, if you dont wany fade anymations you can disable them in you hyprland config in `animations > animation = fadeLayersIn / animation = fadeLayersOut`

> And bad resource usage again.

GTK is again at fault here

> Removing init system and making all of the threads start when program is launched by GUI command

This is how hyprswitch functioned "in the early days". Starting GTK and opening the windows causes a delay thats way to long for hyprswitch to be usable (arround 0.7 seconds). https://github.com/H3rmt/hyprswitch/issues/37

> Adding more customization including showing up animation and changing border radius separately.

You can customize the GTK window using the custom css, but you cant configure animations there as these are not done by GTK
